### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-extent#7]
/cc @Turfjs/owners 

I think we should remove this module from the public API:

* We don't have any other modules that support what it outputs: the contract of GeoJSON ⇢ GeoJSON is broken with this module
* It's named a thing that does not make it obvious that it'll be an array rather than a geojson extent
* Basically, confusion it causes outweighs benefit.

I think we should _keep it for the internal api_.

**Comment by ingalls** [comment]
Just a quick thought as I use this module quite often, what about outputting geojson with the addition of a `bbox` [feature](http://geojson.org/geojson-spec.html#bounding-boxes).

**Comment by tmcw** [comment]
This module is just a proxy for https://github.com/mapbox/geojson-extent which will continue to be usable

**Comment by ingalls** [comment]
:+1:

**Comment by morganherlocker** [comment]
> We don't have any other modules that support what it outputs

@tmcw bboxes are supported as a fundamental component in Turf. For example, bbox-polygon takes it as an input: https://github.com/Turfjs/turf-bbox-polygon

While this is just a wrapper around geojson-extent, exposing it here provides discoverability and curation. A large portion of turf modules are wrappers around things that people *could* use if they knew they existed and took the time to validate them. This is a very commonly required function in the context of Turf use cases, and I think it belongs in the public API. As @ingalls suggests, bboxify is also useful, but this is a distinct function.

Perhaps we could change the name to something that is less confusing? The intended meaning here is "the minimum bbox to cover a set of features", which might have a naming collision with something I am not familiar with.

**Comment by tmcw** [comment]
> For example, bbox-polygon takes it as an input: https://github.com/Turfjs/turf-bbox-polygon

That's the only function that takes bboxes, right?

I think a bboxify function fits the same usecase with less confusion.

**Comment by mourner** [comment]
Not sure about this too. Expecting lots of confused people posting questions like "how do I get a bbox", with us responding "sorry, there's a third-party module for that because this feature was too advanced to include in Turf". Its absence will cause confusion that far outweights the minor inconvenience of reading a short description in the docs.

**Comment by morganherlocker** [comment]
bboxify is modifying the state of a feature. That is what you want in some cases, but in this case I actually want to get the bbox and nothing more. Idk, this might seem pedantic, but I think there is a real distinction here. Only having bboxify is making an assumption about the use case and adding friction for an extremely common operation.

> That's the only function that takes bboxes, right?

Also turf-grid and turf-hex (maybe more, but those are the ones I remember). It really is a fundamental type that isunderstood by turf.

**Comment by tmcw** [comment]
>  Expecting lots of confused people posting questions like "how do I get a bbox"

Why? What would they want a raw bbox for? Like: what would they do with it in turf-land or outside? Maybe there's some usage for raw bboxes somewhere, but it's not nearly important enough to merit the name `turf-extent`, with its basically synonym `turf-envelope` doing something quite different.

Like, I get that bboxes are useful. But

* people assume that things do what they say on the tin and do not read documentation
* the contract of turf is geojson in and geojson out, and bboxes are not geojson.

**Comment by mourner** [comment]
> the contract of turf is geojson in and geojson out, and bboxes are not geojson.

Should we remove `distance`, `area` modules etc.? What would people use area or distance for? Anything really. The same for bboxes — there's a merit to API simplification but we shouldn't treat users like kids playing with fire, and let them do anything they can think of. Especially if it comes to such a common thing.

If you're concerned about name, lets rename it to `turf-bbox`. This makes sense to me because GeoJSON spec has `bbox` as a concept (an array of 4 values), described exactly like the output of the module.

**Comment by lyzidiamond** [comment]
I think changing the name will solve a lot of problems folks are having with this module. There are potentially situations in which it is useful, but the name itself is the confusion point, I think. I vote we keep it as part of the public-facing API, but rename it.

**Comment by tmcw** [comment]
Okay, we're keeping this module and renaming it to bbox.
